import json,os,sys
from integrated_arpg_engine_v10 import IntegratedARPGEngineV10
MASTER=os.environ.get('ANDROMEDA_MASTER_RELEASE','/mnt/data/ANDROMEDA_CODEX_MASTER_V2_0_1_RELEASE.zip');OUT=os.environ.get('ARPG_STAGE10_VALIDATION_OUT','04_REPORTS/ARPG_STAGE10/ARPG_STAGE10_VALIDATION_V1_1_0.json');checks=[]
def ck(n,ok,d=None):checks.append({'name':n,'status':'PASS' if ok else 'FAIL','detail':d})
e=IntegratedARPGEngineV10(':memory:',master_release_path=MASTER);r=e.create_world('val:s10',101010);wid=r['world']['world_instance_id'];m=e.mobility_arpg(wid);it=e.items_arpg(wid);w=e.world_arpg(wid)
v=m.verify();ck('health',e.health_arpg_v10(wid)['status']=='PASS');ck('verify',v['status']=='PASS',v);ck('automotive_canon',m.canonical_snapshot('SYS-AUT-001')['name']=='Quadro funcional de automóveis e veículos de serviço');ck('varden_bridge',m.canonical_snapshot('POI-046')['name']=='Ponte Varden');ck('local_road',m.segment('SRTE-001')['segment_kind']=='CANONICAL_LOCAL_ROAD');ck('boundary_all',all(m.segment(x)['boundary_locked'] for x in m.BOUNDARY_ROUTES));ck('profile_count',len(m.list_vehicle_profiles())==3);ck('derived_connectors',v['derived_local_connectors']>0);ck('bridge_count',v['bridges']>=1)
p=e.arpg(wid).create_profile('val:s10',origin_mode='CREATED',display_name='Val Driver')['profile'];pref=p['profile_ref'];a=m.create_vehicle(pref,'VEH-PROFILE-SERVICE-LIGHT',event_ref='v:create');vr=a['vehicle']['vehicle_ref'];ck('vehicle_create',a['status']=='PASS');ck('cargo_inventory',it.inventory_snapshot(vr)['owner_kind']=='VEHICLE_CARGO');ck('board',m.board(pref,vr,event_ref='v:board',as_driver=True)['status']=='PASS')
s=next(x for x in m.list_segments() if x['segment_kind']=='DERIVED_LOCAL_CONNECTOR');st=w.ensure_profile(pref);st['zone_ref']=s['origin_ref'];st['instance_context']={'kind':'OVERWORLD','ref':s['origin_ref']};w._save_profile(st);vv=m.vehicle(vr);vv['zone_ref']=s['origin_ref'];m._save_vehicle(vv);t=m.travel(pref,vr,s['segment_ref'],event_ref='v:travel');ck('travel',t['status']=='PASS',t);ck('profile_moved',w.ensure_profile(pref)['zone_ref']==t.get('destination_zone'));ck('propulsion_used',t.get('propulsion_used',0)>0);ck('integrity_wear',t.get('integrity_loss',0)>0)
it.grant_item(pref,'MIN-IRON',6,event_ref='v:iron');ld=m.load_cargo(pref,vr,'MIN-IRON',4,event_ref='v:load');ck('load',ld['status']=='PASS');ck('cargo_qty',it.inventory_snapshot(vr)['stacks'].get('MIN-IRON')==4);un=m.unload_cargo(vr,pref,'MIN-IRON',2,event_ref='v:unload');ck('unload',un['status']=='PASS');ck('cargo_remaining',it.inventory_snapshot(vr)['stacks'].get('MIN-IRON')==2)
br=m.set_bridge_condition('POI-046',5);ck('bridge_damage',not br['operational']);
# Canonical local road uses a proximity-derived Varga bridge attachment; broken bridge must block traversal.
local=m.segment('SRTE-001');a,b=m._segment_zone_pair(local);vv=m.vehicle(vr);vv['zone_ref']=a;m._save_vehicle(vv);st=w.ensure_profile(pref);st['zone_ref']=a;st['instance_context']={'kind':'OVERWORLD','ref':a};w._save_profile(st);blocked=m.travel(pref,vr,'SRTE-001',event_ref='v:bridge:block');ck('bridge_blocks_local_road',blocked.get('reason')=='BRIDGE_INOPERABLE',blocked);
m.set_bridge_condition('POI-046',100);ck('bridge_repair',m.bridge('POI-046')['operational']);bd=m.travel(pref,vr,'RTE-003',event_ref='v:boundary');ck('boundary_reject',bd.get('reason')=='BOUNDARY_ROUTE_LOCKED',bd)
# NPC driver + cargo contract
npc=next(n for stt in e.country(wid).world['country']['states'] for b in stt['blocks'] for c in b['cities'] for n in c['npcs'] if n['class']!='CHILD');nv=m.create_vehicle(npc['id'],'VEH-PROFILE-UTILITY-CARGO',event_ref='v:npc:create')['vehicle'];ck('npc_vehicle_zone',nv['zone_ref'] is not None);ck('npc_driver',m.board(npc['id'],nv['vehicle_ref'],event_ref='v:npc:board',as_driver=True)['status']=='PASS')
# same seed infrastructure projection deterministic independent of world UUID
r2=e.create_world('val:s10:2',101010);m2=e.mobility_arpg(r2['world']['world_instance_id']);d1=[s for s in m.list_segments() if s['segment_kind']=='DERIVED_LOCAL_CONNECTOR'];d2=[s for s in m2.list_segments() if s['segment_kind']=='DERIVED_LOCAL_CONNECTOR'];ck('same_seed_segments',[x['segment_ref'] for x in d1]==[x['segment_ref'] for x in d2]);ck('same_seed_distances',[x['distance_km'] for x in d1]==[x['distance_km'] for x in d2]);ck('final_verify',m.verify()['status']=='PASS',m.verify());e.close()
res={'record_id':'ARPG-STAGE10-VALIDATION-V1.1.0','checks':len(checks),'passed':sum(x['status']=='PASS' for x in checks),'failed':sum(x['status']=='FAIL' for x in checks),'status':'PASS' if all(x['status']=='PASS' for x in checks) else 'FAIL','results':checks};os.makedirs(os.path.dirname(OUT),exist_ok=True);open(OUT,'w',encoding='utf-8').write(json.dumps(res,ensure_ascii=False,indent=2,sort_keys=True));print(json.dumps({k:res[k] for k in ('checks','passed','failed','status')}));sys.exit(0 if res['status']=='PASS' else 1)
