import json,os,tempfile,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'01_RUNTIME'))
from living_runtime import LivingRuntime,new_runtime_id,clock_point
from world_systems import WorldSystems
from object_environment import ObjectEnvironmentSystem
from atlas_living_bridge import AtlasLivingBridge,AtlasSnapshotPublisher
MASTER='/mnt/data/ANDROMEDA_CODEX_MASTER_V2_0_1_RELEASE.zip';OUT=ROOT/'05_DEMO/DEMO_RESULT_V1_0.json';PROJ=ROOT/'06_ATLAS_LIVING'
t=tempfile.TemporaryDirectory();db=os.path.join(t.name,'demo.db');snapdir=os.path.join(t.name,'snap');rt=LivingRuntime(db,master_release_path=MASTER);w=rt.create_world('stage13-player',1313,ticks_per_day=24);wid=w['world_instance_id'];ws=WorldSystems(rt);ws.load_master_snapshots(MASTER);ws.bootstrap_world(wid,population_seed=1000)
# player-visible runtime actor and structure
c=rt.get_clock(wid);actor={'state_id':new_runtime_id('state'),'world_instance_id':wid,'timeline_id':w['timeline_id'],'entity_runtime_id':new_runtime_id('agent'),'origin':'RUNTIME_BORN','entity_kind':'AGENT','lifecycle':'ACTIVE','version':0,'updated_at':clock_point(c['day'],c['tick']),'data':{'name':'Jogador Demo','atlas_exposure':'PLAYER_VISIBLE','location_ref':'CIT-001'},'protection':{}};rt.register_entity(wid,actor)
obj=ObjectEnvironmentSystem(rt);prof=obj.register_profile(wid,{'object_class':'BRIDGE','material_class':'STONE','base_integrity':100});bridge=obj.spawn_object(wid,profile_id=prof['profile_id'],data={'name':'Ponte da Timeline','atlas_exposure':'PLAYER_VISIBLE','location_ref':'CIT-001'});obj.interact(wid,actor_ref=actor['entity_runtime_id'],target_ref=bridge['entity_runtime_id'],interaction_type='DAMAGE',amount=100);ws.set_route_operational(wid,'RTE-001',False,reason='PHYSICAL_BRIDGE_DESTROYED')
pub=AtlasSnapshotPublisher(rt,snapdir);m1=pub.publish(wid);b1=AtlasLivingBridge(os.path.join(snapdir,m1['snapshot_file']),MASTER);before=b1.export_projection(wid,role='PLAYER',request_scope='stage13-player',spoiler_max=0,recent_events=500);public=b1.export_projection(role='PUBLIC');admin_before=b1.export_projection(wid,role='ADMIN',spoiler_max=3,recent_events=500);b1.close()
# Seven universe days later the physical object recovers; route is reconciled.
rt.advance_ticks(wid,7*24);rt.process_due_recoveries(wid);ws.set_route_operational(wid,'RTE-001',True,reason='PHYSICAL_BRIDGE_RECOVERED');m2=pub.publish(wid);b2=AtlasLivingBridge(os.path.join(snapdir,m2['snapshot_file']),MASTER);after=b2.export_projection(wid,role='PLAYER',request_scope='stage13-player',spoiler_max=0,recent_events=500);admin_after=b2.export_projection(wid,role='ADMIN',spoiler_max=3,recent_events=500);readonly=b2.write_attempt_probe();b2.close()
def rtstate(p,rid):return next(x for x in p['layers']['LIVE_ENTITY_STATE'] if x['entity_runtime_id']==rid)
def route(p):return next(x for x in p['layers']['LIVE_ROUTES'] if x.get('canonical_ref')=='RTE-001')
be=rtstate(before,bridge['entity_runtime_id']);ae=rtstate(after,bridge['entity_runtime_id']);br=route(before);ar=route(after)
report={'record_id':'STAGE13-DEMO-V1.0','status':'PASS','world_instance_id':wid,'timeline_id':w['timeline_id'],'before':{'day':before['world']['clock']['day'],'bridge_lifecycle':be['lifecycle'],'bridge_integrity':be['data']['integrity'],'route_operational':br['data']['operational'],'events':len(before['layers']['LIVE_EVENTS']),'recoveries':len(before['layers']['LIVE_RECOVERY'])},'after':{'day':after['world']['clock']['day'],'bridge_lifecycle':ae['lifecycle'],'bridge_integrity':ae['data']['integrity'],'route_operational':ar['data']['operational'],'events':len(after['layers']['LIVE_EVENTS']),'history_preserved':len(after['layers']['LIVE_EVENTS'])>=len(before['layers']['LIVE_EVENTS'])},'access':{'public_runtime_access':public['runtime_access'],'player_runtime_access':after['runtime_access'],'admin_runtime_access':admin_after['runtime_access'],'admin_causal_entries':len(admin_after['layers']['LIVE_CAUSAL']),'snapshot_distribution':m2['distribution'],'readonly_probe':readonly},'projection_integrity':{'before':None,'after':None}}
vb=AtlasLivingBridge(os.path.join(snapdir,m1['snapshot_file']),MASTER);va=AtlasLivingBridge(os.path.join(snapdir,m2['snapshot_file']),MASTER);report['projection_integrity']['before']=vb.verify_projection(before)['status'];report['projection_integrity']['after']=va.verify_projection(after)['status'];vb.close();va.close()
# close temporary verification bridges by reopening only for hash checks above is acceptable; explicit conditions below.
ok=report['before']['bridge_lifecycle']=='DESTROYED' and report['before']['route_operational'] is False and report['after']['day']==7 and report['after']['bridge_lifecycle']=='ACTIVE' and report['after']['bridge_integrity']==100 and report['after']['route_operational'] is True and report['after']['history_preserved'] and report['access']['public_runtime_access']=='NONE' and report['access']['player_runtime_access']=='PLAYER_SAFE' and report['access']['admin_runtime_access']=='ADMIN_OPERATIONAL' and readonly=='PASS_READ_ONLY' and all(v=='PASS' for v in report['projection_integrity'].values())
if not ok:report['status']='FAIL'
(PROJ/'LIVING_ATLAS_PROJECTION_BEFORE_DEMO.json').write_text(json.dumps(before,ensure_ascii=False,indent=2),encoding='utf-8');(PROJ/'LIVING_ATLAS_PROJECTION_AFTER_DEMO.json').write_text(json.dumps(after,ensure_ascii=False,indent=2),encoding='utf-8');OUT.write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps(report,ensure_ascii=False));rt.close();t.cleanup();raise SystemExit(0 if report['status']=='PASS' else 1)
