import hashlib,json,re,zipfile,sys
from pathlib import Path
R=Path(__file__).resolve().parents[1]; M=Path('/mnt/data/ANDROMEDA_CODEX_MASTER_V2_0_1_RELEASE.zip'); OUT=R/'04_REPORTS/STAGE13_STATIC_AUDIT_V1_0.json'; BASE=json.load(open(R/'06_ATLAS_LIVING/UPSTREAM_BASELINE_HASHES_V1_0.json',encoding='utf-8'))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
mods=['living_runtime.py','consequence_engine.py','agent_brain.py','social_memory.py','ecology_brain.py','object_environment.py','world_orchestrator.py','world_systems.py','long_horizon.py','llm_gateway.py']
module_rows=[{'module':m,'stage13_sha256':sha(R/'01_RUNTIME'/m),'baseline_sha256':BASE['runtime_modules'][m],'identical':sha(R/'01_RUNTIME'/m)==BASE['runtime_modules'][m]} for m in mods]
atlas_paths=list(BASE['canonical_atlas_runtime']);atlas_rows=[]
with zipfile.ZipFile(M) as z:
 for pth in atlas_paths:
  h=hashlib.sha256(z.read('ANDROMEDA_CODEX_MASTER/'+pth)).hexdigest();atlas_rows.append({'path':pth,'actual_sha256':h,'baseline_sha256':BASE['canonical_atlas_runtime'][pth],'match':h==BASE['canonical_atlas_runtime'][pth]})
bridge=(R/'01_RUNTIME/atlas_living_bridge.py').read_text(encoding='utf-8');js=(R/'06_ATLAS_LIVING/atlas-live-core.mjs').read_text(encoding='utf-8');contract=json.load(open(R/'02_CONTRACTS/ATLAS_CODEX_LIVING_RUNTIME_INTEGRATION_CONTRACT_V1_0.json',encoding='utf-8'));checks=[]
def ck(n,o,d=None):checks.append({'name':n,'status':'PASS' if o else 'FAIL','detail':d})
for x in module_rows:ck('upstream-byte-identical:'+x['module'],x['identical'],x)
for x in atlas_rows:ck('canonical-atlas-manifest:'+x['path'],x['match'],x)
for n,o in [('bridge-mode-ro','?mode=ro' in bridge),('bridge-query-only','PRAGMA query_only=ON' in bridge),('bridge-no-network-import',not re.search(r'^\s*(import|from)\s+(requests|httpx|urllib|socket|aiohttp)',bridge,re.M)),('bridge-no-eval','eval(' not in bridge),('bridge-no-exec','exec(' not in bridge),('bridge-no-todo',not re.search(r'TODO|FIXME',bridge,re.I)),('public-role',"role=='PUBLIC'" in bridge),('player-owner-scope','owner_scope' in bridge and 'player scope mismatch' in bridge),('admin-role',"role=='ADMIN'" in bridge),('level4-hidden','level<4' in bridge),('hidden-atlas-filter',"atlas_visibility')!='HIDDEN'" in bridge),('recursive-redaction','REDACTED_CANONICAL_REF' in bridge and 'REDACTED_RUNTIME_REF' in bridge),('llm-raw-not-exposed',"'raw_content_exposed':False" in bridge),('snapshot-backup-api','.backup(dst)' in bridge),('snapshot-backend-only','BACKEND_ONLY_DO_NOT_SERVE_DB_FILE' in bridge),('snapshot-0600','os.chmod(target,0o600)' in bridge),('snapshot-core-integrity','full_integrity_check(world_instance_id)' in bridge),('row-hash-checks','state_hash' in bridge and 'relationship_hash' in bridge and 'population_hash' in bridge),('projection-hash','projection_hash' in bridge and 'verify_projection' in bridge),('js-readonly-assert','runtime_write_authority !== false' in js),('js-no-fetch','fetch(' not in js),('js-no-storage-write',not re.search(r'localStorage\.(setItem|removeItem)|indexedDB|XMLHttpRequest',js)),('contract-json-only',contract.get('transport',{}).get('client_delivery')=='JSON_PROJECTION_ONLY'),('contract-backend-snapshot',contract.get('transport',{}).get('snapshot_file_distribution')=='BACKEND_ONLY_0600'),('master-release-hash',hashlib.sha256(M.read_bytes()).hexdigest()=='6d9ac3cce7dcf6a65fdcf73859c332a0211c1af52d149077beef554bf7bbd0b2')]:ck(n,o)
failed=[c for c in checks if c['status']=='FAIL'];rep={'record_id':'STAGE13-STATIC-AUDIT-V1.0','checks':len(checks),'passed':len(checks)-len(failed),'failed':len(failed),'status':'PASS' if not failed else 'FAIL','upstream_modules':module_rows,'canonical_atlas_runtime':atlas_rows,'failures':failed};OUT.write_text(json.dumps(rep,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps({'status':rep['status'],'checks':rep['checks'],'failed':rep['failed']}));raise SystemExit(0 if not failed else 1)
